apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: "davtalks-gitops-front-staging"
  labels:
    app: "davtalks-gitops-front-staging"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "davtalks-gitops-front-staging"
  template:
    metadata:
      labels:
        app: "davtalks-gitops-front-staging"
    spec:
      containers:
        - name: "davtalks-gitops-front-staging"
          image: "nginx:1.7.9"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: "davtalks-gitops-front-staging"
spec:
  type: LoadBalancer
  selector:
    app: "davtalks-gitops-front-staging"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
