apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: "davtalks-gitops-back-staging"
  labels:
    app: "davtalks-gitops-back-staging"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "davtalks-gitops-back-staging"
  template:
    metadata:
      labels:
        app: "davtalks-gitops-back-staging"
    spec:
      containers:
        - name: "davtalks-gitops-back-staging"
          image: "nginx:1.7.9"
          env:
            - name: NODE_ENV
              value: "staging"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: "davtalks-gitops-back-staging"
spec:
  type: LoadBalancer
  selector:
    app: "davtalks-gitops-back-staging"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000